@startuml Brand Translation - Update Activity
!theme plain
skinparam backgroundColor #FFFFFF
skinparam activityFontSize 12
skinparam activityFontColor #333333
skinparam activityBorderColor #666666
skinparam activityBackgroundColor #F7F7F7

Brand Brand Translation Update Activity: execute the validated workflow

start
:Brand Brand Translation Update Activity: execute the validated workflow;
:brandTranslation.update({ where: id & deletedAt=null, data: {..., updatedById} });
if (condition?) then (Yes)
  :Brand Brand Translation Update Activity: execute the validated workflow;
  stop
else (OK)
  if (condition?) then (Yes)
    :Brand Brand Translation Update Activity: execute the validated workflow;
  else (No)
    :Build message i18n;
    :Brand Brand Translation Update Activity: execute the validated workflow;
  endif
endif
stop

@enduml


