@startuml Brand Translation - Detail Activity
!theme plain
skinparam backgroundColor #FFFFFF
skinparam activityFontSize 12
skinparam activityFontColor #333333
skinparam activityBorderColor #666666
skinparam activityBackgroundColor #F7F7F7

Brand Brand Translation Detail Activity: execute the validated workflow

start
:Brand Brand Translation Detail Activity: execute the validated workflow;
:findUnique where id & deletedAt=null;
if (condition?) then (Yes)
  :Build message i18n;
  :Brand Brand Translation Detail Activity: execute the validated workflow;
else (No)
  :Brand Brand Translation Detail Activity: execute the validated workflow;
endif
stop

@enduml


