@startuml Brand Translation - Create Activity
!theme plain
skinparam backgroundColor #FFFFFF
skinparam activityFontSize 12
skinparam activityFontColor #333333
skinparam activityBorderColor #666666
skinparam activityBackgroundColor #F7F7F7

Brand Brand Translation Create Activity: execute the validated workflow

start
:Brand Brand Translation Create Activity: execute the validated workflow;
:brandTranslation.create({ createdById, data });
if (condition?) then (Yes)
  :Brand Brand Translation Create Activity: execute the validated workflow;
  stop
else (OK)
  :Build message i18n;
  :Brand Brand Translation Create Activity: execute the validated workflow;
endif
stop

@enduml


