@startuml Brand - Detail Activity
!theme plain
skinparam backgroundColor #FFFFFF
skinparam activityFontSize 12
skinparam activityFontColor #333333
skinparam activityBorderColor #666666
skinparam activityBackgroundColor #F7F7F7

Brand Brand Detail Activity: execute the validated workflow

start
:Brand Brand Detail Activity: execute the validated workflow;
:Brand Brand Detail Activity: execute the validated workflow;
:findUnique include translations theo languageId;
if (condition?) then (Yes)
  :Build message i18n;
  :Brand Brand Detail Activity: execute the validated workflow;
else (No)
  :Brand Brand Detail Activity: execute the validated workflow;
endif
stop

@enduml


