@startuml Language - Create Activity
!theme plain
skinparam backgroundColor #FFFFFF
skinparam activityFontSize 12
skinparam activityFontColor #333333
skinparam activityBorderColor #666666
skinparam activityBackgroundColor #F7F7F7

Language Language Create Activity: execute the validated workflow

start
:Language Language Create Activity: execute the validated workflow;
:language.create({ createdById, data });
:Build message i18n;
:Language Language Create Activity: execute the validated workflow;
stop

@enduml


