@startuml Media - Presigned URL Activity
!theme plain
skinparam backgroundColor #FFFFFF
skinparam activityFontSize 12
skinparam activityFontColor #333333
skinparam activityBorderColor #666666
skinparam activityBackgroundColor #F7F7F7

Media Media Presigned Url Activity: execute the validated workflow

start
:Media Media Presigned Url Activity: execute the validated workflow;
:generateRandomFilename(filename);
:S3 createPresignedUrlWithClient(randomFilename);
:Media Media Presigned Url Activity: execute the validated workflow;
:Build message i18n;
:Media Media Presigned Url Activity: execute the validated workflow;
stop

@enduml


