import { Discount, DiscountGetAllResponse, DiscountType, DiscountStatus, DiscountApplyType, VoucherType } from '@/types/discount.interface';

const mockDiscounts: Discount[] = [
  {
    id: 'd1',
    name: 'English content normalized from the original source text.',
    description: 'English content normalized from the original source text.',
    code: 'SUMMER20',
    value: 20,
    maxDiscountValue: 50000,
    minOrderValue: 100000,
    startDate: new Date('2025-06-01').toISOString(),
    endDate: new Date('2025-08-31').toISOString(),
    maxUses: 1000,
    usesCount: 150,
    maxUsesPerUser: 1,
    usersUsed: [],
    shopId: 'shop1',
    isPlatform: false,
    voucherType: VoucherType.SHOP,
    discountType: DiscountType.PERCENTAGE,
    discountApplyType: DiscountApplyType.ALL,
    discountStatus: DiscountStatus.ACTIVE,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'd2',
    name: 'English content normalized from the original source text.',
    description: 'English content normalized from the original source text.',
    code: 'PLATFORM100K',
    value: 100000,
    minOrderValue: 500000,
    startDate: new Date('2025-07-01').toISOString(),
    endDate: new Date('2025-07-31').toISOString(),
    maxUses: 500,
    usesCount: 450,
    maxUsesPerUser: 1,
    usersUsed: [],
    shopId: '', // Platform voucher
    isPlatform: true,
    voucherType: VoucherType.SHOP, // Or any other relevant type for platform
    discountType: DiscountType.FIX_AMOUNT,
    discountApplyType: DiscountApplyType.ALL,
    discountStatus: DiscountStatus.ACTIVE,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'd3',
    name: 'English content normalized from the original source text.',
    description: 'English content normalized from the original source text.',
    code: 'FREESHIP15K',
    value: 15000,
    maxDiscountValue: 15000,
    minOrderValue: 0,
    startDate: new Date('2025-01-01').toISOString(),
    endDate: new Date('2025-12-31').toISOString(),
    maxUses: 10000,
    usesCount: 9800,
    maxUsesPerUser: 5,
    usersUsed: [],
    shopId: '',
    isPlatform: true,
    voucherType: VoucherType.PRODUCT, // Assuming freeship is a type of product voucher
    discountType: DiscountType.FIX_AMOUNT,
    discountApplyType: DiscountApplyType.ALL,
    discountStatus: DiscountStatus.EXPIRED,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'd4',
    name: 'English content normalized from the original source text.',
    description: 'English content normalized from the original source text.',
    code: 'PRIVATE4U',
    value: 99000,
    minOrderValue: 300000,
    startDate: new Date('2025-07-15').toISOString(),
    endDate: new Date('2025-07-20').toISOString(),
    maxUses: 1,
    usesCount: 0,
    maxUsesPerUser: 1,
    usersUsed: [],
    shopId: 'shop2',
    isPlatform: false,
    voucherType: VoucherType.PRIVATE,
    discountType: DiscountType.FIX_AMOUNT,
    discountApplyType: DiscountApplyType.SPECIFIC,
    discountStatus: DiscountStatus.INACTIVE,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const mockDiscountResponse: DiscountGetAllResponse = {
  statusCode: 200,
  message: 'Success',
  data: mockDiscounts,
  metadata: {
    totalItems: mockDiscounts.length,
    page: 1,
    limit: 10,
    totalPages: Math.ceil(mockDiscounts.length / 10),
  },
};
