@startuml Cart - Add To Cart Activity
!theme plain
skinparam backgroundColor #FFFFFF
skinparam activityFontSize 12
skinparam activityFontColor #333333
skinparam activityBorderColor #666666
skinparam activityBackgroundColor #F7F7F7

Cart Cart Add To Cart Activity: execute the validated workflow

start
:Cart Cart Add To Cart Activity: execute the validated workflow;
:Cart Cart Add To Cart Activity: execute the validated workflow;
:Cart Cart Add To Cart Activity: execute the validated workflow;
if (condition?) then (Yes)
  :Cart Cart Add To Cart Activity: execute the validated workflow;
  :Cart Cart Add To Cart Activity: execute the validated workflow;
  :Build message i18n;
  :Cart Cart Add To Cart Activity: execute the validated workflow;
else (No)
  :Cart Cart Add To Cart Activity: execute the validated workflow;
endif
stop

@enduml


