@startuml Review - Update Activity
!theme plain
skinparam backgroundColor #FFFFFF
skinparam activityFontSize 12
skinparam activityFontColor #333333
skinparam activityBorderColor #666666
skinparam activityBackgroundColor #F7F7F7

Review Review Update Activity: execute the validated workflow

start
:Review Review Update Activity: execute the validated workflow;
:validateOrder(orderId,userId) & validateUpdateReview(reviewId,userId);
if (condition?) then (Yes)
  :BEGIN TRANSACTION;
  :review.update (increment updateCount);
  :reviewMedia.deleteMany(reviewId);
  :reviewMedia.createManyAndReturn(medias);
  :COMMIT;
  :Build message i18n;
  :Review Review Update Activity: execute the validated workflow;
else (No)
  :Review Review Update Activity: execute the validated workflow;
endif
stop

@enduml


