@startuml User - Delete Activity
!theme plain
skinparam backgroundColor #FFFFFF
skinparam activityFontSize 12
skinparam activityFontColor #333333
skinparam activityBorderColor #666666
skinparam activityBackgroundColor #F7F7F7

User User Delete Activity: execute the validated workflow

start
:User User Delete Activity: execute the validated workflow;
:verifyYourself(user.userId, id);
if (condition?) then (Yes)
  :User User Delete Activity: execute the validated workflow;
  stop
endif
:User User Delete Activity: execute the validated workflow;
:verifyRole(roleNameAgent, roleIdTarget);
if (condition?) then (Yes)
  :User User Delete Activity: execute the validated workflow;
  stop
endif
:Soft delete user (deletedAt, deletedById);
:Build message i18n;
:User User Delete Activity: execute the validated workflow;
stop

@enduml


