@startuml User Management Activity Diagram
!theme plain
skinparam backgroundColor #FFFFFF
skinparam activityFontSize 12
skinparam activityFontColor #333333
skinparam activityBorderColor #666666
skinparam activityBackgroundColor #F0F0F0
skinparam activityDiamondBackgroundColor #FFE6E6
skinparam activityDiamondBorderColor #CC0000

User User Management Activity: execute the validated workflow

start

:User User Management Activity: execute the validated workflow;

if (condition?) then (Yes)
  :User User Management Activity: execute the validated workflow;
  :User User Management Activity: execute the validated workflow;
  :User User Management Activity: execute the validated workflow;
  if (condition?) then (Yes)
    :User User Management Activity: execute the validated workflow;
    :User User Management Activity: execute the validated workflow;
    note right
      Database Operations:
      • User User Management Activity: execute the validated workflow
      • User User Management Activity: execute the validated workflow
      • Parallel execution cho performance
      end note
    :Include role information;
    :User User Management Activity: execute the validated workflow;
    :User User Management Activity: execute the validated workflow;
    :User User Management Activity: execute the validated workflow;
  else (No)
    :User User Management Activity: execute the validated workflow;
  endif

else (No)
  :GET /users/:userId;
  :User User Management Activity: execute the validated workflow;
  :User User Management Activity: execute the validated workflow;
  if (condition?) then (Yes)
    :User User Management Activity: execute the validated workflow;
    :findUniqueIncludeRolePermissions;
    :User User Management Activity: execute the validated workflow;
    if (condition?) then (Yes)
      :User User Management Activity: execute the validated workflow;
      :User User Management Activity: execute the validated workflow;
    else (No)
      :User User Management Activity: execute the validated workflow;
      :User User Management Activity: execute the validated workflow;
    endif
  else (No)
    :User User Management Activity: execute the validated workflow;
  endif

else (No)
  :POST /users + user data;
  :User User Management Activity: execute the validated workflow;
  :User User Management Activity: execute the validated workflow;
  :User User Management Activity: execute the validated workflow;
  note right
    Data Validation:
    • email: string validation
    • name: string validation
    • phoneNumber: string validation
    • avatar: string validation
    • status: enum validation
    • password: string validation
    • roleId: string validation
    end note
  if (condition?) then (Yes)
    :User User Management Activity: execute the validated workflow;
    :User User Management Activity: execute the validated workflow;
    if (condition?) then (Yes)
      :User User Management Activity: execute the validated workflow;
    else (No)
      :User User Management Activity: execute the validated workflow;
      :User User Management Activity: execute the validated workflow;
      if (condition?) then (Yes)
        :User User Management Activity: execute the validated workflow;
        :User User Management Activity: execute the validated workflow;
      endif
    endif
    :User User Management Activity: execute the validated workflow;
    :User User Management Activity: execute the validated workflow;
    :User User Management Activity: execute the validated workflow;
    if (condition?) then (Yes)
      if (condition?) then (Yes)
        :User User Management Activity: execute the validated workflow;
        :User User Management Activity: execute the validated workflow;
      else (No)
        :User User Management Activity: execute the validated workflow;
        :User User Management Activity: execute the validated workflow;
      endif
    else (No)
      :User User Management Activity: execute the validated workflow;
      :User User Management Activity: execute the validated workflow;
    endif
  else (No)
    :User User Management Activity: execute the validated workflow;
  endif

else (No)
  :PUT /users/:userId + user data;
  :User User Management Activity: execute the validated workflow;
  :User User Management Activity: execute the validated workflow;
  :User User Management Activity: execute the validated workflow;
  if (condition?) then (Yes)
    :User User Management Activity: execute the validated workflow;
    :User User Management Activity: execute the validated workflow;
    if (condition?) then (Yes)
      :User User Management Activity: execute the validated workflow;
      :User User Management Activity: execute the validated workflow;
    else (No)
      :User User Management Activity: execute the validated workflow;
      :User User Management Activity: execute the validated workflow;
      if (condition?) then (Yes)
        :User User Management Activity: execute the validated workflow;
        :User User Management Activity: execute the validated workflow;
        if (condition?) then (Yes)
          :User User Management Activity: execute the validated workflow;
        else (No)
          :User User Management Activity: execute the validated workflow;
          :User User Management Activity: execute the validated workflow;
          if (condition?) then (Yes)
            :User User Management Activity: execute the validated workflow;
            :User User Management Activity: execute the validated workflow;
          endif
        endif
        :User User Management Activity: execute the validated workflow;
        :User User Management Activity: execute the validated workflow;
        if (condition?) then (Yes)
          if (condition?) then (Yes)
            if (condition?) then (Yes)
              :User User Management Activity: execute the validated workflow;
              :User User Management Activity: execute the validated workflow;
            else (No)
              :User User Management Activity: execute the validated workflow;
              :User User Management Activity: execute the validated workflow;
            endif
          else (No)
            :User User Management Activity: execute the validated workflow;
            :User User Management Activity: execute the validated workflow;
          endif
        else (No)
          :User User Management Activity: execute the validated workflow;
          :User User Management Activity: execute the validated workflow;
        endif
      else (No)
        :User User Management Activity: execute the validated workflow;
        :User User Management Activity: execute the validated workflow;
      endif
    endif
  else (No)
    :User User Management Activity: execute the validated workflow;
  endif

else (No)
  :DELETE /users/:userId;
  :User User Management Activity: execute the validated workflow;
  :User User Management Activity: execute the validated workflow;
  if (condition?) then (Yes)
    :User User Management Activity: execute the validated workflow;
    :User User Management Activity: execute the validated workflow;
    if (condition?) then (Yes)
      :User User Management Activity: execute the validated workflow;
      :User User Management Activity: execute the validated workflow;
    else (No)
      :User User Management Activity: execute the validated workflow;
      :User User Management Activity: execute the validated workflow;
      if (condition?) then (Yes)
        :User User Management Activity: execute the validated workflow;
        :User User Management Activity: execute the validated workflow;
        if (condition?) then (Yes)
          :User User Management Activity: execute the validated workflow;
        else (No)
          :User User Management Activity: execute the validated workflow;
          :User User Management Activity: execute the validated workflow;
          if (condition?) then (Yes)
            :User User Management Activity: execute the validated workflow;
            :User User Management Activity: execute the validated workflow;
          endif
        endif
        :User User Management Activity: execute the validated workflow;
        :User User Management Activity: execute the validated workflow;
        :User User Management Activity: execute the validated workflow;
        :User User Management Activity: execute the validated workflow;
      else (No)
        :User User Management Activity: execute the validated workflow;
        :User User Management Activity: execute the validated workflow;
      endif
    endif
  else (No)
    :User User Management Activity: execute the validated workflow;
  endif

else (Invalid operation)
  :User User Management Activity: execute the validated workflow;
endif

:User User Management Activity: execute the validated workflow;

stop

@enduml
