@startuml Order - Get List Activity
!theme plain
skinparam backgroundColor #FFFFFF
skinparam activityFontSize 12
skinparam activityFontColor #333333
skinparam activityBorderColor #666666
skinparam activityBackgroundColor #F7F7F7

Order Order List Activity: execute the validated workflow

start
:Order Order List Activity: execute the validated workflow;
:Order Order List Activity: execute the validated workflow;
:Order Order List Activity: execute the validated workflow;
:Order Order List Activity: execute the validated workflow;
:Order Order List Activity: execute the validated workflow;
:Build message i18n;
:Order Order List Activity: execute the validated workflow;
stop

@enduml


