@startuml Category - Get List Activity
!theme plain
skinparam backgroundColor #FFFFFF
skinparam activityFontSize 12
skinparam activityFontColor #333333
skinparam activityBorderColor #666666
skinparam activityBackgroundColor #F7F7F7

Category Category List Activity: execute the validated workflow

start
:Category Category List Activity: execute the validated workflow;
:Category Category List Activity: execute the validated workflow;
:Query category.findMany with include translations theo languageId;
:Category Category List Activity: execute the validated workflow;
:Build message i18n;
:Category Category List Activity: execute the validated workflow;
stop

@enduml


