@startuml Auth - Register Activity
!theme plain
skinparam backgroundColor #FFFFFF
skinparam activityFontSize 12
skinparam activityFontColor #333333
skinparam activityBorderColor #666666
skinparam activityBackgroundColor #F7F7F7

Auth Auth Register Activity: execute the validated workflow

start
:Auth Auth Register Activity: execute the validated workflow;
:validateVerificationCode(REGISTER);
if (condition?) then (Yes)
  :Hash password;
  fork
    :Auth Auth Register Activity: execute the validated workflow;
  fork again
    :Auth Auth Register Activity: execute the validated workflow;
  end fork
  :Auth Auth Register Activity: execute the validated workflow;
else (No)
  :Auth Auth Register Activity: execute the validated workflow;
endif
stop

@enduml


